# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='lookup_name',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
    ]
