# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 14:17
from __future__ import unicode_literals

import analysis.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis', '0030_auto_20160610_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=256, upload_to=analysis.models.get_temporary_download_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporarydownload', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
