# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import orio.utils
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0031_auto_20160630_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenomeAssembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('chromosome_size_file', utils.models.DynamicFilePathField(max_length=128, path=orio.utils.get_data_path, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='analysis',
            name='genome_assembly_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.GenomeAssembly'),
        ),
        migrations.AddField(
            model_name='featurelist',
            name='genome_assembly_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.GenomeAssembly'),
        ),
        migrations.AddField(
            model_name='genomicdataset',
            name='genome_assembly_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.GenomeAssembly'),
        ),
    ]
