# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 13:52
from __future__ import unicode_literals

from django.db import migrations

from orio import validators


def setGenomeAssemblies(apps, schema_editor):
    GenomeAssembly = apps.get_model("analysis", "GenomeAssembly")
    Analysis = apps.get_model("analysis", "Analysis")
    FeatureList = apps.get_model("analysis", "FeatureList")
    GenomicDataset = apps.get_model("analysis", "GenomicDataset")

    hg19 = GenomeAssembly.objects.create(
        name='hg19',
        chromosome_size_file=validators.get_chromosome_size_path('hg19'),
    )

    mm9 = GenomeAssembly.objects.create(
        name='mm9',
        chromosome_size_file=validators.get_chromosome_size_path('mm9'),
    )

    for Cls in [Analysis, FeatureList, GenomicDataset]:
        Cls.objects\
            .filter(genome_assembly=1)\
            .update(genome_assembly_new=hg19)

        Cls.objects\
            .filter(genome_assembly=2)\
            .update(genome_assembly_new=mm9)


def unsetGenomeAssemblies(apps, schema_editor):
    GenomeAssembly = apps.get_model("analysis", "GenomeAssembly")
    GenomeAssembly.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0032_create_genome_assembly'),
    ]

    operations = [
        migrations.RunPython(
            setGenomeAssemblies,
            reverse_code=unsetGenomeAssemblies)
    ]
