# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0034_swap_genome_assembly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurelist',
            name='borrowers',
        ),
        migrations.RemoveField(
            model_name='genomicdataset',
            name='borrowers',
        ),
        migrations.RemoveField(
            model_name='sortvector',
            name='borrowers',
        ),
    ]
