# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 14:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0035_auto_20160725_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurelist',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featurelist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='genomicdataset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genomicdataset', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sortvector',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sortvector', to=settings.AUTH_USER_MODEL),
        ),
    ]
