# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import orio.utils
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0036_auto_20160725_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='genomeassembly',
            name='annotation_file',
            field=utils.models.DynamicFilePathField(max_length=128, null=True, path=orio.utils.get_data_path, unique=True),
        ),
    ]
