# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 18:42
from __future__ import unicode_literals

from django.db import migrations

from orio.validators import base


def setGenomeAnnotation(apps, schema_editor):
    GenomeAssembly = apps.get_model("analysis", "GenomeAssembly")

    for ga in GenomeAssembly.objects.all():
        ga.annotation_file = base.get_annotation_file_path(ga.name)
        ga.save()


def unsetGenomeAnnotation(apps, schema_editor):
    GenomeAssembly = apps.get_model("analysis", "GenomeAssembly")

    for ga in GenomeAssembly.objects.all():
        ga.annotation_file = None
        ga.save()


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0037_auto_20160819_1437'),
    ]

    operations = [
        migrations.RunPython(
            setGenomeAnnotation,
            reverse_code=unsetGenomeAnnotation)
    ]
