# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 16:05
from __future__ import unicode_literals

from django.db import migrations, models


def setGenomeAnnotation(apps, schema_editor):
    GenomeAssembly = apps.get_model("analysis", "GenomeAssembly")

    for ga in GenomeAssembly.objects.all():
        ga.annotation_file = base.get_annotation_file_path(ga.name)
        ga.save()


def unsetGenomeAnnotation(apps, schema_editor):
    GenomeAssembly = apps.get_model("analysis", "GenomeAssembly")

    for ga in GenomeAssembly.objects.all():
        ga.annotation_file = None
        ga.save()


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0039_auto_20160819_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='slug',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='featurelist',
            name='slug',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='genomicdataset',
            name='slug',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='sortvector',
            name='slug',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
