# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 16:06
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify
from itertools import chain


def setSlugs(apps, schema_editor):
    Analysis = apps.get_model("analysis", "Analysis")
    FeatureList = apps.get_model("analysis", "FeatureList")
    GenomicDataset = apps.get_model("analysis", "GenomicDataset")
    SortVector = apps.get_model("analysis", "SortVector")

    for obj in chain(
            Analysis.objects.all(),
            FeatureList.objects.all(),
            GenomicDataset.objects.all(),
            SortVector.objects.all()):
        obj.slug = slugify(obj.name)
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0040_auto_20160824_1205'),
    ]

    operations = [
        migrations.RunPython(
            setSlugs,
            reverse_code=migrations.RunPython.noop)
    ]
