# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0041_auto_20160824_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='slug',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='featurelist',
            name='slug',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='genomicdataset',
            name='slug',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='sortvector',
            name='slug',
            field=models.CharField(max_length=128),
        ),
    ]
