# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-22 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0043_auto_20160922_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sortvector',
            old_name='vector',
            new_name='dataset',
        ),
    ]
